pom.xml

Upgrade Keycloak to v23.0.3 for integration tests
- Upgrade Keycloak to v23.0.3 for integration tests
inter-team …

MODUSERSKC-3 Upgrade Keycloak to v23.0.3 for integration tests

---

src/main/resources/swagger.api/users-keycloak.yaml

Fix Open API schemas to pass api-lint validations
- Update schemas
inter-team dependencies increase.
While it's …

Fix open api schemas

---

pom.xml
src/main/java/org/folio/uk/domain/UserMigrationJobRepository.java
src/main/java/org/folio/uk/domain/entity/EntityUserMigrationJobStatus.java
src/main/java/org/folio/uk/domain/entity/UserMigrationJobEntity.java
src/main/java/org/folio/uk/integration/configuration/model/Config.java
src/main/java/org/folio/uk/integration/configuration/model/Configurations.java
src/main/java/org/folio/uk/integration/login/model/PasswordResetAction.java
src/main/java/org/folio/uk/integration/notify/model/Context.java
src/main/java/org/folio/uk/integration/notify/model/Notification.java
src/main/java/org/folio/uk/migration/UserMigrationService.java

The official version of Spring for Quesnelia is 3.2 (see https://wiki.folio.org/display/TC/Quesnelia).
- upgrade spring-boot to 3.2.0
- fix issues
environment. Communication is paramount if that is to be achieved, especially …

MODUSERSKC-2: upgrade spring-boot version to 3.2.0

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
src/main/resources/swagger.api/users-keycloak.yaml

[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)

FOLIO-3678 MODUSERSKC-1 Use GitHub Workflows api-lint and api-schema-lint and api-doc

---

pom.xml

Update module version
- Update artifact version to 1.1.0
inter-team dependencies increase.
While it's helpful …

Update module version

---

Jenkinsfile
pom.xml
src/test/resources/wiremock/stubs/users/create-module-system-user.json
src/test/resources/wiremock/stubs/users/update-user-id-notmatch.json
src/test/resources/wiremock/stubs/users/update-user-no-auth.json
src/test/resources/wiremock/stubs/users/update-user-notfound.json
src/test/resources/wiremock/stubs/users/update-user.json

Fix build issues with insufficient resources by changing Jenkins build node to "bigmem"
inter-team dependencies …

Change Jenkins build node to "bigmem"

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/uk/integration/policy/PolicyService.java
src/main/java/org/folio/uk/service/UserService.java

https://issues.folio.org/browse/MODUSERSKC-13
- delete order matters - validation for user/capabilities (capability-set) endpoints
- add required interfaces
- add module permissions
environment. Communication is paramount if …

MODUSERSKC-13 User policy remains after user deleted

---

src/main/java/org/folio/uk/integration/keycloak/KeycloakService.java
src/main/java/org/folio/uk/integration/keycloak/model/KeycloakUser.java
src/test/java/org/folio/uk/base/BaseIntegrationTest.java
src/test/java/org/folio/uk/it/UserIT.java
src/test/java/org/folio/uk/it/UserMigrationIT.java
src/test/java/org/folio/uk/support/TestConstants.java
src/test/resources/json/user/search-users-migration.json
src/test/resources/wiremock/stubs/users/create-user-auth-exist.json
src/test/resources/wiremock/stubs/users/create-user.json
src/test/resources/wiremock/stubs/users/update-user-id-notmatch.json
src/test/resources/wiremock/stubs/users/update-user-no-auth.json
src/test/resources/wiremock/stubs/users/update-user-notfound.json
src/test/resources/wiremock/stubs/users/update-user.json

https://folio-org.atlassian.net/browse/MODUSERSKC-15
add new user keycloak attribute
update tests
inter-team …

MODUSERSKC-15: Create new user attribute in Keycloak:  external_system_id

---

pom.xml

Raises folio-backend-testing to v1.3.0-SNAPSHOT
- Raise `folio-backend-testing` to v1.3.0-SNAPSHOT
inter-team …

KEYCLOAK-6 Raise folio-backend-testing to v1.3.0-SNAPSHOT

---

descriptors/ModuleDescriptor-template.json

https://folio-org.atlassian.net/browse/MODROLESKC-152
To resolve permissions conflicts with mod-users, permissions in mod-users-keycloak should be updated.
- update descriptor's permissions
environment. Communication is …

MODROLESKC-152: update md permissions

---

NEWS.md
pom.xml

Release v1.2.0
https://folio-org.atlassian.net/browse/MODUSERSKC-25
- use maven release plugin
- update NEWS.md …

MODUSERSKC-25: release 1.2.0

---

NEWS.md
src/main/java/org/folio/uk/service/UserService.java
src/test/java/org/folio/uk/it/UserIT.java

[MODUSERSKC-28](https://folio-org.atlassian.net/browse/MODUSERSKC-28)
Error when saving updates to users that were not migrated.
- Add eventual consistency on update operation
environment. Communication is paramount if that …

MODUSERSKC-28

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Release 1.3.0
Prepare for the next iteration

Release 1.3.0

---

descriptors/ModuleDescriptor-template.json

https://folio-org.atlassian.net/browse/MODUSERSKC-29
Add permissoins for endpoint to protect.
- change module descriptor template
environment. Communication is paramount if that is to be achieved, especially as the number of …

MODUSERSKC-29: protect endpoint by permissions

---

NEWS.md
src/main/resources/swagger.api/schemas/personal.json
src/test/resources/json/user/get-user-response.json
src/test/resources/wiremock/stubs/users/get-user.json

https://folio-org.atlassian.net/browse/EUREKA-95
Looking through network requests, the file is uploaded (I see the POST request to users/profile-picture but never retrieved (no corresponding GET users/profile-picture/${picture-UUID} as there is in folio-snapshot). It appears the personal.profilePictureLink attribute that contains the id of the uploaded picture is missing in the response from the GET request to users-keycloak/users/${user-UUID}. 
- add profile picture ling
- update tests
- What other modules will these changes …

EUREKA-95: add profile picture

---

NEWS.md
pom.xml

- prepare release v1.5.0
- prepare for next development iteration

Release 1.5.0

---

src/main/java/org/folio/uk/integration/kafka/KafkaMessageListener.java
src/main/java/org/folio/uk/integration/keycloak/SystemUserService.java
src/main/java/org/folio/uk/service/UserService.java
src/test/java/org/folio/uk/integration/kafka/KafkaMessageListenerTest.java
src/test/java/org/folio/uk/integration/keycloak/SystemUserServiceTest.java
src/test/java/org/folio/uk/it/SystemUserIT.java
src/test/java/org/folio/uk/service/UserServiceTest.java
src/test/java/org/folio/uk/support/TestConstants.java
src/test/resources/json/kafka/system-user-delete-event.json
src/test/resources/json/kafka/system-user-update-event.json
src/test/resources/wiremock/stubs/capabilities/assign-system-user-capability.json
src/test/resources/wiremock/stubs/capabilities/query-capabilities-by-permission.json
src/test/resources/wiremock/stubs/policy/find-policy-by-system-username.json
src/test/resources/wiremock/stubs/users/delete-system-user.json
src/test/resources/wiremock/stubs/users/find-system-user-by-query.json
src/test/resources/wiremock/stubs/users/get-system-user-capability-set.json
src/test/resources/wiremock/stubs/users/get-system-user-capability.json
src/test/resources/wiremock/stubs/users/get-system-user-roles.json

Add handling of delete and update system user events
- Add handling of delete and update system user events …

MODUSERSKC-11: Add handling of delete and update system user events

---

Jenkinsfile

Related Jira ticket:
[RANCHER-1515: prepare & merge PRs for RANCHER-1502 part1](https://folio-org.atlassian.net/browse/RANCHER-1515)

RANCHER-1515: pack application into Docker Image and save to Image Store

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/MODUSERSKC-44

Release 1.5.1

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/uk/controller/AuthUserController.java
src/main/java/org/folio/uk/controller/UserController.java
src/main/java/org/folio/uk/integration/keycloak/KeycloakService.java
src/main/java/org/folio/uk/integration/keycloak/model/KeycloakUser.java
src/main/java/org/folio/uk/service/UserService.java
src/main/resources/swagger.api/users-keycloak.yaml
src/test/java/org/folio/uk/controller/AuthUserControllerTest.java
src/test/java/org/folio/uk/it/AuthUserIT.java
src/test/resources/wiremock/stubs/users/get-user-no-username.json

Provide an API to verify and ensure existence of Keycloak user records corresponding to Folio user records (within a specific Tenant)
US: [MODUSERSKC-30](https://folio-org.atlassian.net/browse/MODUSERSKC-30)
Provide two API endpoints - one to verify existence of Keycloak user record for a given Folio user record, and another to ensure existence (e.g. create if missing) of such Keycloak user record. Both APIs take Folio user ID as an input, and provide HTTP status codes as an output.
- What other modules will these changes …

MODUSERSKC-30: API to verify and ensure existence of Keycloak user records corresponding to Folio user records 

---

NEWS.md
pom.xml

Release 1.5.3

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/MODUSERSKC-53

Release 1.6.0

---

pom.xml

Increases keycloak-admin-client to v25.0.6
- Increases keycloak-admin-client to v25.0.6
- Use the latest snapshot versions of `applications-poc-tools` library components
environment. Communication is paramount if that is to …

KEYCLOAK-24 Increase keycloak-client to v25.0.6

---

src/main/resources/swagger.api/schemas/policy/policy.json
src/main/resources/swagger.api/schemas/policy/policyLogicType.json
src/main/resources/swagger.api/schemas/policy/rolePolicy.json
src/main/resources/swagger.api/schemas/policy/sourceType.json
src/main/resources/swagger.api/schemas/policy/timePolicy.json
src/main/resources/swagger.api/schemas/policy/userPolicy.json
src/test/resources/wiremock/stubs/policy/find-policy-by-username.json
src/test/resources/wiremock/stubs/policy/update-policy.json

[[MODUSERSKC-58] Update role related enum values to upper case](https://folio-org.atlassian.net/browse/MODUSERSKC-58)
- Update policy "logic" field enum to be uppercase

[MODUSERSKC-58] Update role related enum values to upper case

---

descriptors/ModuleDescriptor-template.json

To add the permission introduced in MODNOTIFY-134
inter-team dependencies increase.
While it's helpful for …

[MODUSERSKC-57] - Add the permission "notify.users.item.post"

---

NEWS.md
src/main/java/org/folio/uk/integration/roles/UserCapabilitiesClient.java
src/main/java/org/folio/uk/integration/roles/UserCapabilitySetClient.java
src/main/java/org/folio/uk/integration/roles/UserRolesClient.java
src/main/java/org/folio/uk/service/UserService.java
src/test/java/org/folio/uk/it/UserIT.java
src/test/java/org/folio/uk/service/UserServiceTest.java
src/test/resources/wiremock/stubs/users/get-user-capability-notfound.json
src/test/resources/wiremock/stubs/users/get-user-capability-set-notfound.json
src/test/resources/wiremock/stubs/users/get-user-roles-notfound.json

[MODUSERSKC-67
](https://folio-org.atlassian.net/browse/MODUSERSKC-67)
A user without a Keycloak record exists in the system.
If a user is created in the UI (or via the API using the POST /users call), and no capabilities, credentials, or roles are assigned to it, that user would not have a Keycloak record.
A user is deleted without errors. The modal is closed, the deleted user’s detailed view is closed, and the deleted user disappears from the users list.
- Handle 404 from the mod-roles-keycloak
- What other modules will …

MODUSERSKC-67 Error when deleting a user without Keycloak record

---

pom.xml

Increases version of `keycloak-admin-client` to `v26.0.4`, also implement a new version of keycloak in integration tests - `v26.1.0`
- Increases version of `keycloak-admin-client` to `v26.0.4`
- Increases version of `applications-poc-tools` to `v2.3.0-SNAPSHOT`
Ideally, all the PRs involved in breaking changes would be merged on the same …

KEYCLOAK-25 Upgrade keycloak-client to v26.0.4

---

descriptors/ModuleDescriptor-template.json

Update capabilities and user-capabilities interfaces version
inter-team dependencies increase.
While it's …

Update capabilities and user-capabilities interfaces version

---

NEWS.md
pom.xml
src/main/resources/swagger.api/schemas/personal.json
src/main/resources/swagger.api/schemas/user.json
src/test/java/org/folio/uk/support/TestConstants.java
src/test/resources/wiremock/stubs/users/create-module-system-user.json
src/test/resources/wiremock/stubs/users/update-user-id-notmatch.json
src/test/resources/wiremock/stubs/users/update-user-no-auth.json
src/test/resources/wiremock/stubs/users/update-user-notfound.json
src/test/resources/wiremock/stubs/users/update-user.json

Backport the issue: https://folio-org.atlassian.net/browse/MODUSERSKC-94
---

Release v3.0.4 (Sunflower CSP)

---

NEWS.md
README.md
src/main/resources/application.yml
src/test/resources/application-it.yml

Revert Use SECURE_STORE_ENV, not ENV, for secure store key
Revert  Use SECURE_STORE_ENV, not ENV, for secure store key
---

MODUSERSKC-99 - revert Use SECURE_STORE_ENV, not ENV, for secure store key
